platform :ios, '9.0'

target 'beerApiListaFavoritosRealm' do
  use_frameworks!

    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'
    pod 'AlamofireObjectMapper'
    pod 'MBProgressHUD'
    pod 'RealmSwift'

end
